### ISSUE TITLE
S2 P1 - Bug - Failing Redirect on Loginpage

### ISSUE THREAD

**Issue by MaxSeier** [muhlba91/fh-burgenland-bswe-3b#16]
Bug Report: Redirect onto Account Page not working after Login via Login-Page

Environment:
Version: 2.1.0
Browser: Chrome v114
Depl. Stage: Prodcution

Classification: S2
Steps: Login via the Login Page (after input of correct Username, Password)
Expected Outcome: Redirect onto Account Page
Actual Outcome: No redirect
Optional: -

**Comment by muhlba91** [comment]
S2: are you sure this doesn't have more impact? is the app still usable if after logging in nothing happens? for a more "tech savvy" user it probably is fine if they open the right URL but for the common user this could actually be a S1/P1 bug.

it's a pretty crisp and short description. i'd be a bit more verbose with the first sentence to explain the context more.
it's a thin line between just enough and not enough - i can argue that you can phrase it clearer but i also acknowledge that all information is there and it becomes apparent on what the issue is. :)
